q = Queue(5)
q.enqueue(3)
q.enqueue(13)
q.enqueue(2)
q.enqueue(6)
q.enqueue(7)
print("remove element", q.dequeue())
print("remove element", q.dequeue())
print("remove element", q.dequeue())
print("remove element", q.dequeue())
print("remove element", q.dequeue())
print("remove element", q.dequeue())
q.display()